### ISSUE TITLE
Allow for more than one image pull secret

### ISSUE THREAD

**Issue by chrisbsmith** [MapLarge/helm-charts#16]
We should allow for multiple image pull secrets

https://github.com/MapLarge/helm-charts/blob/4ff3c0fd506ed129e6b350e6f6242f958ddb10db/charts/maplarge/templates/statefulset.yaml#L49-L52

Could look to do something like this instead:

```
imagePullSecrets:
{{ range .Values.image.imagePullSecrets }}
- {{ . }}
{{ end }}
```

`values.yaml`
```
image:
  imagePullSecrets:
    - name: maplarge-dockerhub-pull-secret
    - name: image-secret-2
```
